import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LeagueHeader, leagueScreenStyles as base } from '../../components/leagues/LeagueUI';
import { playedLeagueMatches } from '../../data/leaguePreviewData';
import LeaguePlayerAvatar from '../../components/leagues/LeaguePlayerAvatar';

const EVENT_ICONS = { goal: 'football', yellow: 'albums' };

export default function LeagueMatchDetailScreen({ route, navigation }) {
  const match = playedLeagueMatches.find((item) => item.id === route.params?.matchId) || playedLeagueMatches[0];
  const [tab, setTab] = useState('summary');
  return <View style={base.screen}><ScrollView contentContainerStyle={base.content} showsVerticalScrollIndicator={false}>
    <Pressable onPress={() => navigation.navigate('LeagueCalendar')} style={styles.back}><Ionicons name="arrow-back" size={18} color="#fff"/><Text style={styles.backText}>Calendario</Text></Pressable>
    <LeagueHeader title="Ficha del partido" subtitle={`Jornada ${match.round} · ${match.venue}`} />
    <View style={styles.scoreboard}>
      <Text style={styles.finished}>FINALIZADO</Text>
      <View style={styles.scoreRow}><Text style={styles.club}>{match.home}</Text><Text style={styles.bigScore}>{match.homeScore}  -  {match.awayScore}</Text><Text style={[styles.club,{textAlign:'right'}]}>{match.away}</Text></View>
      <Text style={styles.date}>{match.date}</Text>
    </View>
    <View style={styles.mvp}><LeaguePlayerAvatar name={match.mvp.name} photoUrl={match.mvp.leaguePhotoUrl} size={43} featured/><View style={{flex:1}}><Text style={styles.mvpLabel}>MVP DEL PARTIDO</Text><Text style={styles.mvpName}>{match.mvp.name}</Text><Text style={styles.mvpTeam}>{match.mvp.team}</Text></View><View style={styles.mvpStats}><Text style={styles.mvpNumber}>{match.mvp.goals}</Text><Text style={styles.mvpStatLabel}>GOLES</Text></View><View style={styles.mvpStats}><Text style={styles.mvpNumber}>{match.mvp.assists}</Text><Text style={styles.mvpStatLabel}>ASIST.</Text></View></View>
    <View style={styles.tabs}>{[['summary','Eventos'],['lineups','Alineaciones'],['report','Acta']].map(([key,label])=><Pressable key={key} onPress={()=>setTab(key)} style={[styles.tab,tab===key&&styles.activeTab]}><Text style={[styles.tabText,tab===key&&styles.activeText]}>{label}</Text></Pressable>)}</View>
    {tab === 'summary' && <View style={styles.timeline}>{match.events.map((event,index)=><View key={`${event.minute}-${index}`} style={styles.event}><View style={styles.minute}><Text style={styles.minuteText}>{event.minute}'</Text></View><View style={[styles.eventIcon,event.type==='yellow'&&styles.yellow]}><Ionicons name={EVENT_ICONS[event.type] || 'ellipse'} size={14} color={event.type==='yellow'?'#171717':'#ff6a17'}/></View><View style={{flex:1}}><Text style={styles.eventPlayer}>{event.player}</Text><Text style={styles.eventDetail}>{event.detail} · {event.team==='home'?match.home:match.away}</Text></View></View>)}</View>}
    {tab === 'lineups' && <View><Lineup title={match.home} players={match.lineups.home}/><Lineup title={match.away} players={match.lineups.away}/><Text style={styles.disclaimer}>Alineaciones iniciales del encuentro.</Text></View>}
    {tab === 'report' && <View style={base.card}><Info icon="person-outline" label="Árbitro" value={match.report.referee}/><Info icon="time-outline" label="Duración" value={match.report.duration}/><Info icon="people-outline" label="Asistencia" value={match.report.attendance}/><View style={styles.notes}><Text style={styles.infoLabel}>OBSERVACIONES</Text><Text style={base.muted}>{match.report.notes}</Text></View></View>}
  </ScrollView></View>;
}
function Lineup({title,players}){return <View style={base.card}><Text style={styles.lineupTitle}>{title}</Text>{players.map((player,index)=><View key={player} style={styles.lineupPlayer}><Text style={styles.playerNumber}>{index+1}</Text><LeaguePlayerAvatar name={player.replace(/ \(POR\)$/,'')} photoUrl={null} size={30}/><Text style={styles.playerName}>{player}</Text>{index<7&&<Text style={styles.starter}>TITULAR</Text>}</View>)}</View>}
function Info({icon,label,value}){return <View style={styles.info}><Ionicons name={icon} size={18} color="#ff6a17"/><View><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>}
const styles=StyleSheet.create({back:{flexDirection:'row',alignItems:'center',gap:7,alignSelf:'flex-start',marginBottom:18},backText:{color:'#b9bbc2',fontSize:12,fontWeight:'800'},scoreboard:{padding:20,borderRadius:22,backgroundColor:'#15171d',borderWidth:1,borderColor:'#292c34',marginBottom:10},finished:{color:'#7c8089',fontSize:9,fontWeight:'900',letterSpacing:1,textAlign:'center'},scoreRow:{flexDirection:'row',alignItems:'center',marginVertical:20},club:{flex:1,color:'#fff',fontSize:15,fontWeight:'900'},bigScore:{color:'#fff',fontSize:27,fontWeight:'900',marginHorizontal:10},date:{color:'#777b84',fontSize:11,textAlign:'center'},mvp:{flexDirection:'row',alignItems:'center',gap:11,padding:14,borderRadius:18,backgroundColor:'#17191f',borderWidth:1,borderColor:'rgba(255,90,0,.23)',marginBottom:14},mvpIcon:{width:40,height:40,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,90,0,.09)'},mvpLabel:{color:'#ff7a2f',fontSize:8,fontWeight:'900',letterSpacing:.7},mvpName:{color:'#fff',fontSize:14,fontWeight:'900',marginTop:3},mvpTeam:{color:'#777b84',fontSize:10,marginTop:2},mvpStats:{alignItems:'center'},mvpNumber:{color:'#fff',fontSize:18,fontWeight:'900'},mvpStatLabel:{color:'#6d7078',fontSize:7,fontWeight:'900'},tabs:{flexDirection:'row',padding:4,borderRadius:14,backgroundColor:'#111319',marginBottom:14},tab:{flex:1,alignItems:'center',paddingVertical:10,borderRadius:10},activeTab:{backgroundColor:'#22252d'},tabText:{color:'#747780',fontSize:11,fontWeight:'900'},activeText:{color:'#ff6a17'},timeline:{paddingVertical:3},event:{flexDirection:'row',alignItems:'center',minHeight:64,borderBottomWidth:1,borderBottomColor:'#1d2027'},minute:{width:36},minuteText:{color:'#888c95',fontSize:12,fontWeight:'900'},eventIcon:{width:30,height:30,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,90,0,.08)',marginRight:11},yellow:{backgroundColor:'#f0c830'},eventPlayer:{color:'#fff',fontSize:13,fontWeight:'900'},eventDetail:{color:'#747780',fontSize:10,marginTop:3},lineupTitle:{color:'#fff',fontSize:17,fontWeight:'900',marginBottom:11},lineupPlayer:{flexDirection:'row',alignItems:'center',minHeight:42,borderTopWidth:1,borderTopColor:'#20232a'},playerNumber:{width:28,color:'#ff6a17',fontSize:11,fontWeight:'900'},playerName:{flex:1,color:'#d8d9dd',fontSize:12,fontWeight:'700'},starter:{color:'#676b74',fontSize:7,fontWeight:'900'},disclaimer:{color:'#666a72',fontSize:10,marginTop:1},info:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#22252c'},infoLabel:{color:'#71757e',fontSize:8,fontWeight:'900',letterSpacing:.6,textTransform:'uppercase'},infoValue:{color:'#fff',fontSize:13,fontWeight:'800',marginTop:3},notes:{paddingTop:16,gap:7}});
