CREATE TABLE IF NOT EXISTS scheduled_match_publications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  field_id BIGINT UNSIGNED NULL,
  field_name VARCHAR(255) NULL,
  starts_at DATETIME NOT NULL,
  publish_at DATETIME NOT NULL,
  duration_min INT NOT NULL DEFAULT 60,
  price_eur DECIMAL(10,2) NOT NULL DEFAULT 0,
  easypass_cost INT NOT NULL DEFAULT 1,
  capacity INT NOT NULL,
  has_aftergame TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('pending','publishing','published','cancelled','failed') NOT NULL DEFAULT 'pending',
  published_match_id BIGINT UNSIGNED NULL,
  error_message VARCHAR(500) NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  published_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_scheduled_publish_queue (status, publish_at),
  KEY idx_scheduled_creator (created_by, created_at)
);
