import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../api/client';
import { colors, layout, radii, spacing, typography } from '../theme';
import ScreenHeader from '../components/ScreenHeader';

const WEIGHTS = { outfield:[.2,.2,.2,.25,.15], goalkeeper:[.3,.15,.25,.15,.15] };
const GUIDE = ['1–2 Muy negativo','3–4 Bajo','5 Correcto','6 Buen partido','7 Notable','8 Sobresaliente','9 De los mejores','10 Excepcional'];
const makeDraft = (item) => ({ ...item, criterion_1:item.criterion_1 || 5, criterion_2:item.criterion_2 || 5, criterion_3:item.criterion_3 || 5, criterion_4:item.criterion_4 || 5, criterion_5:item.criterion_5 || 5, observations:item.observations || '', manual_score:item.manual_score == null ? '' : String(item.manual_score), manual_reason:item.manual_reason || '' });
const scoreFor = (draft) => Math.round([1,2,3,4,5].reduce((total,index) => total + Number(draft[`criterion_${index}`]) * WEIGHTS[draft.player_role || 'outfield'][index - 1], 0) * 10) / 10;

function EvaluationCard({ draft, labels, onChange, onSave, onNotEvaluable, saving }) {
  const computed = scoreFor(draft);
  const finalScore = draft.manual_score !== '' ? Number(draft.manual_score) : computed;
  const updateNote = (key, delta) => onChange({ ...draft, [key]:Math.min(10, Math.max(1, Number(draft[key]) + delta)) });
  return (
    <View style={[styles.card, draft.status === 'completed' && styles.cardDone]}>
      <View style={styles.playerTop}><View style={styles.avatar}><Text style={styles.avatarText}>{String(draft.name || '?').slice(0,1).toUpperCase()}</Text></View><View style={{ flex:1 }}><Text style={styles.playerName}>{draft.name}</Text><Text style={styles.playerMeta}>{draft.status === 'completed' ? 'Valorado' : draft.status === 'not_evaluable' ? 'No evaluable' : 'Pendiente'}</Text></View><View style={styles.score}><Text style={styles.scoreValue}>{Number.isFinite(finalScore) ? finalScore.toFixed(1) : computed.toFixed(1)}</Text><Text style={styles.scoreLabel}>NOTA</Text></View></View>
      <View style={styles.objectives}><Text style={styles.objective}>⚽ {draft.goals || 0}</Text><Text style={styles.objective}>🎯 {draft.assists || 0}</Text><Text style={styles.objective}>{draft.is_mvp ? '⭐ MVP' : 'Sin MVP'}</Text><Text style={styles.objective}>{draft.result === 'win' ? 'Victoria' : draft.result === 'loss' ? 'Derrota' : draft.result === 'draw' ? 'Empate' : 'Sin resultado'}</Text></View>
      <View style={styles.roleRow}><Text style={styles.roleText}>Portero</Text><Switch value={draft.player_role === 'goalkeeper'} onValueChange={(value) => onChange({ ...draft, player_role:value ? 'goalkeeper' : 'outfield' })} trackColor={{ false:'#34373D', true:'#78520B' }} thumbColor={draft.player_role === 'goalkeeper' ? colors.orange : '#D7D8DA'} /></View>
      {labels.map((label,index) => { const key = `criterion_${index + 1}`; return <View key={key} style={styles.criterion}><View style={{ flex:1 }}><Text style={styles.criterionLabel}>{label}</Text><Text style={styles.weight}>{Math.round(WEIGHTS[draft.player_role || 'outfield'][index] * 100)}%</Text></View><TouchableOpacity style={styles.noteButton} onPress={() => updateNote(key,-1)}><Ionicons name="remove" size={18} color={colors.white} /></TouchableOpacity><Text style={styles.note}>{draft[key]}</Text><TouchableOpacity style={styles.noteButton} onPress={() => updateNote(key,1)}><Ionicons name="add" size={18} color={colors.white} /></TouchableOpacity></View>; })}
      <TextInput style={[styles.input,styles.observations]} multiline placeholder="Observaciones (opcional)" placeholderTextColor={colors.textSubtle} value={draft.observations} onChangeText={(observations) => onChange({ ...draft, observations })} />
      <View style={styles.manualHeader}><Text style={styles.inputLabel}>Ajuste manual (opcional)</Text><Text style={styles.calculated}>Calculada: {computed.toFixed(1)}</Text></View>
      <TextInput style={styles.input} keyboardType="decimal-pad" placeholder="Nota final del 1 al 10" placeholderTextColor={colors.textSubtle} value={draft.manual_score} onChangeText={(manual_score) => onChange({ ...draft, manual_score:manual_score.replace(',', '.') })} />
      {draft.manual_score !== '' ? <TextInput style={styles.input} placeholder="Motivo obligatorio del ajuste" placeholderTextColor={colors.textSubtle} value={draft.manual_reason} onChangeText={(manual_reason) => onChange({ ...draft, manual_reason })} /> : null}
      <View style={styles.actions}><TouchableOpacity disabled={saving} style={styles.secondaryButton} onPress={onNotEvaluable}><Text style={styles.secondaryText}>No evaluable</Text></TouchableOpacity><TouchableOpacity disabled={saving} style={styles.primaryButton} onPress={onSave}><Text style={styles.primaryText}>{saving ? 'Guardando…' : 'Guardar'}</Text></TouchableOpacity></View>
    </View>
  );
}

export default function AdminCompetitiveEvaluationScreen({ route, navigation }) {
  const matchId = Number(route?.params?.matchId);
  const [data, setData] = useState(null); const [drafts,setDrafts] = useState({}); const [loading,setLoading] = useState(true); const [saving,setSaving] = useState(null); const [error,setError] = useState('');
  const load = useCallback(async () => { try { setLoading(true); setError(''); const response = await api.get(`/admin/competitive/matches/${matchId}/evaluations`); const result=response.data?.data; setData(result); setDrafts(Object.fromEntries((result?.evaluations || []).map((item) => [item.id,makeDraft(item)]))); } catch (requestError) { setError(requestError?.response?.data?.msg || 'No se pudieron cargar las valoraciones.'); } finally { setLoading(false); } },[matchId]);
  useFocusEffect(useCallback(() => { load(); },[load]));
  const items = useMemo(() => data?.evaluations?.map((item) => drafts[item.id]).filter(Boolean) || [],[data,drafts]);
  const payload = (draft) => ({ ...draft, manual_score:draft.manual_score === '' ? null : Number(draft.manual_score) });
  const saveOne = async (draft) => { try { setSaving(draft.id); await api.put(`/admin/competitive/evaluations/${draft.id}`,payload(draft)); await load(); } catch (requestError) { Alert.alert('No se pudo guardar',requestError?.response?.data?.msg || 'Revisa las notas introducidas.'); } finally { setSaving(null); } };
  const saveAll = async () => { try { setSaving('all'); await api.put(`/admin/competitive/matches/${matchId}/evaluations`,{ evaluations:items.filter((item) => item.status !== 'not_evaluable').map(payload) }); await load(); Alert.alert('Valoraciones guardadas','El estado del partido se ha actualizado.'); } catch (requestError) { Alert.alert('No se pudo guardar',requestError?.response?.data?.msg || 'Revisa todas las notas.'); } finally { setSaving(null); } };
  const notEvaluable = (draft) => { if (!draft.observations.trim()) return Alert.alert('Falta el motivo','Escribe el motivo en observaciones antes de marcarlo como no evaluable.'); Alert.alert('Marcar como no evaluable',`¿Confirmas que ${draft.name} no debe puntuar?`,[{ text:'Cancelar',style:'cancel' },{ text:'Confirmar',style:'destructive',onPress:async()=>{ try { setSaving(draft.id); await api.post(`/admin/competitive/evaluations/${draft.id}/not-evaluable`,{ observations:draft.observations }); await load(); } catch(e) { Alert.alert('Error',e?.response?.data?.msg || 'No se pudo guardar.'); } finally { setSaving(null); } } }]); };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.orange} /></View>;
  const labelsFor = (draft) => data?.criteria?.[draft.player_role || 'outfield'] || [];
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><ScreenHeader eyebrow={`SEMANA ${data?.match?.week_number || ''}`} title={data?.match?.field_name || 'Valoración del partido'} description={`${data?.match?.resolved_players || 0} de ${data?.match?.eligible_players || 0} jugadores resueltos`} />
    <View style={styles.guide}><Text style={styles.guideTitle}>Guía de notas</Text><View style={styles.guideWrap}>{GUIDE.map((item)=><Text key={item} style={styles.guideItem}>{item}</Text>)}</View></View>
    {error ? <Text style={styles.error}>{error}</Text> : null}
    {items.map((draft)=><EvaluationCard key={draft.id} draft={draft} labels={labelsFor(draft)} saving={saving===draft.id} onChange={(next)=>setDrafts((current)=>({ ...current,[draft.id]:next }))} onSave={()=>saveOne(draft)} onNotEvaluable={()=>notEvaluable(draft)} />)}
    {items.length ? <TouchableOpacity style={styles.saveAll} disabled={saving === 'all'} onPress={saveAll}><Ionicons name="save-outline" size={19} color="#171109" /><Text style={styles.saveAllText}>{saving === 'all' ? 'Guardando todas…' : 'Guardar todas las valoraciones'}</Text></TouchableOpacity> : null}
    <TouchableOpacity style={styles.back} onPress={() => navigation.goBack()}><Text style={styles.backText}>Volver a partidos pendientes</Text></TouchableOpacity>
  </ScrollView>;
}

const styles=StyleSheet.create({
  screen:{ flex:1,backgroundColor:colors.background },content:{ width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',padding:layout.screenPadding,paddingBottom:spacing(6) },center:{ flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background },
  guide:{ backgroundColor:'#151A20',borderRadius:radii.medium,borderWidth:1,borderColor:colors.border,padding:spacing(1.25),marginBottom:spacing(1.5) },guideTitle:{ color:colors.white,...typography.bodyStrong },guideWrap:{ flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:9 },guideItem:{ color:colors.textMuted,fontSize:11,backgroundColor:'#23272E',paddingHorizontal:8,paddingVertical:5,borderRadius:8 },
  card:{ backgroundColor:colors.surface,borderRadius:radii.large,borderWidth:1,borderColor:colors.border,padding:spacing(1.5),marginBottom:spacing(1.5) },cardDone:{ borderColor:'rgba(85,214,139,.45)' },playerTop:{ flexDirection:'row',alignItems:'center',gap:10 },avatar:{ width:44,height:44,borderRadius:15,backgroundColor:'#2A2418',alignItems:'center',justifyContent:'center' },avatarText:{ color:colors.orange,fontSize:18,fontWeight:'900' },playerName:{ color:colors.white,...typography.heading },playerMeta:{ color:colors.textSubtle,...typography.caption },score:{ alignItems:'center',minWidth:54 },scoreValue:{ color:'#FFD45A',fontSize:25,fontWeight:'900' },scoreLabel:{ color:colors.textSubtle,fontSize:9,fontWeight:'800' },
  objectives:{ flexDirection:'row',flexWrap:'wrap',gap:7,marginVertical:spacing(1.25) },objective:{ color:colors.textMuted,fontSize:11,backgroundColor:'#25282E',borderRadius:8,paddingHorizontal:8,paddingVertical:6 },roleRow:{ flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:7,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border },roleText:{ color:colors.white,...typography.bodyStrong },criterion:{ flexDirection:'row',alignItems:'center',gap:7,paddingVertical:11,borderBottomWidth:1,borderBottomColor:colors.border },criterionLabel:{ color:colors.white,...typography.body },weight:{ color:colors.textSubtle,...typography.caption },noteButton:{ width:34,height:34,borderRadius:11,backgroundColor:'#2A2E34',alignItems:'center',justifyContent:'center' },note:{ width:25,textAlign:'center',color:'#FFD45A',fontSize:18,fontWeight:'900' },
  input:{ color:colors.white,backgroundColor:'#1A1D22',borderWidth:1,borderColor:colors.border,borderRadius:radii.small,paddingHorizontal:12,paddingVertical:11,marginTop:10 },observations:{ minHeight:76,textAlignVertical:'top' },manualHeader:{ flexDirection:'row',justifyContent:'space-between',marginTop:spacing(1.25) },inputLabel:{ color:colors.white,...typography.bodyStrong },calculated:{ color:colors.textMuted,...typography.caption },actions:{ flexDirection:'row',gap:10,marginTop:spacing(1.25) },secondaryButton:{ flex:1,minHeight:46,borderRadius:radii.small,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center' },secondaryText:{ color:colors.textMuted,...typography.bodyStrong },primaryButton:{ flex:1,minHeight:46,borderRadius:radii.small,backgroundColor:colors.orange,alignItems:'center',justifyContent:'center' },primaryText:{ color:'#171109',...typography.bodyStrong,fontWeight:'900' },
  saveAll:{ minHeight:54,borderRadius:radii.medium,backgroundColor:'#FFD45A',flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center' },saveAllText:{ color:'#171109',...typography.bodyStrong,fontWeight:'900' },back:{ alignItems:'center',padding:spacing(1.5) },backText:{ color:colors.textMuted,...typography.body },error:{ color:colors.danger,textAlign:'center',marginBottom:spacing(1) },
});
