import { useCallback, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../api/client';
import { colors, layout, radii, spacing, typography } from '../theme';
import ScreenHeader from '../components/ScreenHeader';

const OUTCOMES={ promoted:{ label:'Ascenso',color:'#55D68B',icon:'arrow-up' },relegated:{ label:'Descenso',color:'#FF667A',icon:'arrow-down' },champion:{ label:'Campeón',color:'#FFD45A',icon:'trophy' },maintained:{ label:'Permanencia',color:'#62B6FF',icon:'remove' } };
const dateRange=(start,end)=>`${new Date(start).toLocaleDateString('es-ES',{ day:'numeric',month:'short' })} – ${new Date(end).toLocaleDateString('es-ES',{ day:'numeric',month:'short',year:'numeric' })}`;

export default function CompetitiveHistoryScreen() {
  const [data,setData]=useState({ seasons:[],badges:[],rewards:[] }); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{ try { setLoading(true);setError('');const response=await api.get('/competitive/me/history');setData(response.data?.data || { seasons:[],badges:[],rewards:[] }); } catch(e) { setError(e?.response?.data?.msg || 'No se pudo cargar el historial.'); } finally { setLoading(false); } },[]);
  useFocusEffect(useCallback(()=>{ load(); },[load]));
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.orange} /></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <ScreenHeader eyebrow="TU LEGADO" title="Historial competitivo" description="Temporadas, movimientos de división, insignias y recompensas." />
    {error ? <Text style={styles.error}>{error}</Text> : null}
    <Text style={styles.section}>Temporadas</Text>
    {data.seasons.length ? data.seasons.map((season)=>{ const outcome=OUTCOMES[season.outcome] || OUTCOMES.maintained; return <View key={season.id} style={styles.seasonCard}><View style={styles.row}><View style={{ flex:1 }}><Text style={styles.seasonName}>{season.name}</Text><Text style={styles.muted}>{dateRange(season.starts_at,season.ends_at)}</Text></View><View style={[styles.outcome,{ borderColor:outcome.color }]}><Ionicons name={outcome.icon} size={14} color={outcome.color} /><Text style={[styles.outcomeText,{ color:outcome.color }]}>{outcome.label}</Text></View></View><View style={styles.stats}><View><Text style={styles.statValue}>#{season.division_position}</Text><Text style={styles.statLabel}>posición</Text></View><View><Text style={styles.statValue}>{Number(season.total_score).toFixed(1)}</Text><Text style={styles.statLabel}>puntos</Text></View><View><Text style={[styles.statValue,{ color:season.next_division_color }]}>{season.next_division_name}</Text><Text style={styles.statLabel}>siguiente división</Text></View></View></View>; }) : <Text style={styles.empty}>Tu historial aparecerá cuando finalice tu primera temporada.</Text>}
    <Text style={styles.section}>Insignias</Text>
    <View style={styles.badgeGrid}>{data.badges.length ? data.badges.map((badge)=><View key={badge.id} style={styles.badge}><View style={[styles.badgeIcon,{ backgroundColor:`${badge.color_hex}20`,borderColor:badge.color_hex }]}><Ionicons name={badge.icon} size={24} color={badge.color_hex} /></View><Text style={styles.badgeName}>{badge.name}</Text><Text style={styles.badgeSeason}>{badge.season_name}</Text></View>) : <Text style={styles.empty}>Aún no has desbloqueado insignias.</Text>}</View>
    <Text style={styles.section}>Recompensas</Text>
    {data.rewards.length ? data.rewards.map((reward)=><View key={reward.id} style={styles.reward}><Ionicons name="gift" size={25} color="#FFD45A" /><View style={{ flex:1 }}><Text style={styles.rewardTitle}>{reward.title}</Text><Text style={styles.muted}>{reward.description}</Text><Text style={styles.rewardStatus}>{reward.status==='available' ? 'DISPONIBLE' : reward.status.toUpperCase()}</Text></View></View>) : <Text style={styles.empty}>Las recompensas se mostrarán aquí cuando las consigas.</Text>}
  </ScrollView>;
}

const styles=StyleSheet.create({ screen:{ flex:1,backgroundColor:colors.background },content:{ width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',padding:layout.screenPadding,paddingBottom:spacing(6) },center:{ flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background },section:{ color:colors.white,...typography.heading,marginTop:spacing(1),marginBottom:spacing(1.25) },seasonCard:{ backgroundColor:colors.surface,borderRadius:radii.large,borderWidth:1,borderColor:colors.border,padding:spacing(1.5),marginBottom:spacing(1) },row:{ flexDirection:'row',alignItems:'center',gap:8 },seasonName:{ color:colors.white,...typography.heading },muted:{ color:colors.textMuted,...typography.caption,marginTop:3 },outcome:{ flexDirection:'row',alignItems:'center',gap:4,borderWidth:1,borderRadius:99,paddingHorizontal:9,paddingVertical:6 },outcomeText:{ fontSize:11,fontWeight:'900' },stats:{ flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderTopColor:colors.border,marginTop:spacing(1.25),paddingTop:spacing(1.25) },statValue:{ color:colors.white,fontSize:17,fontWeight:'900' },statLabel:{ color:colors.textSubtle,fontSize:10,marginTop:2 },badgeGrid:{ flexDirection:'row',flexWrap:'wrap',gap:spacing(1),marginBottom:spacing(1) },badge:{ width:'31%',flexGrow:1,minWidth:100,alignItems:'center',backgroundColor:colors.surface,borderRadius:radii.medium,borderWidth:1,borderColor:colors.border,padding:spacing(1.25) },badgeIcon:{ width:48,height:48,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center' },badgeName:{ color:colors.white,fontSize:12,fontWeight:'800',textAlign:'center',marginTop:8 },badgeSeason:{ color:colors.textSubtle,fontSize:9,textAlign:'center',marginTop:3 },reward:{ flexDirection:'row',gap:12,backgroundColor:'#1E1A10',borderRadius:radii.medium,borderWidth:1,borderColor:'rgba(255,212,90,.28)',padding:spacing(1.25),marginBottom:spacing(1) },rewardTitle:{ color:'#FFD45A',...typography.bodyStrong },rewardStatus:{ color:'#55D68B',fontSize:10,fontWeight:'900',marginTop:7 },empty:{ color:colors.textMuted,...typography.body,textAlign:'center',backgroundColor:colors.surface,borderRadius:radii.medium,padding:spacing(2),marginBottom:spacing(1.5) },error:{ color:colors.danger,textAlign:'center' } });
