import React,{useCallback,useState}from'react';
import{ActivityIndicator,Alert,RefreshControl,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{Ionicons}from'@expo/vector-icons';
import{api}from'../api/client';
import ScreenHeader from'../components/ScreenHeader';

const META={friend_request:['person-add-outline','#8b5cf6'],friend_accepted:['people-outline','#22c55e'],match_invitation:['football-outline','#ff5a00'],group_invitation:['people-circle-outline','#ff5a00'],match_cancelled:['close-circle-outline','#ef4444'],match_updated:['calendar-outline','#f59e0b'],match_reminder:['alarm-outline','#38bdf8'],easypass_gift:['gift-outline','#22c55e'],news:['megaphone-outline','#38bdf8']};
const dateLabel=value=>{if(!value)return'';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleString('es-ES',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});};

export default function NotificationsScreen({navigation}){
  const[data,setData]=useState(null),[refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{try{const response=await api.get('/social/notifications');setData(response.data);}catch{Alert.alert('Notificaciones','No se pudieron cargar tus avisos.');}},[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  const readAll=async()=>{try{await api.patch('/social/notifications/read-all');setData(current=>({...current,unread_count:0,items:current.items.map(item=>({...item,read_at:item.read_at||new Date().toISOString()}))}));}catch{Alert.alert('Notificaciones','No se pudieron marcar como leídas.');}};
  const openItem=async item=>{if(!item.read_at){api.patch(`/social/notifications/${item.id}/read`).catch(()=>{});setData(current=>({...current,unread_count:Math.max(0,current.unread_count-1),items:current.items.map(row=>row.id===item.id?{...row,read_at:new Date().toISOString()}:row)}));}const target=item.data?.screen;if(target){const{screen,...params}=item.data;navigation.navigate(screen,params);}};
  if(!data)return<View style={s.page}><ActivityIndicator color="#ff5a00" style={{marginTop:90}}/></View>;
  return<View style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} tintColor="#ff5a00" onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false);}}/>}>
    <ScreenHeader eyebrow={`${data.unread_count} SIN LEER`} title="Notificaciones" description="Todo lo importante de tus partidos y tu comunidad, en un solo lugar." action={<TouchableOpacity style={s.back} onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" color="#fff" size={21}/></TouchableOpacity>}/>
    <View style={s.actions}><TouchableOpacity style={s.action} onPress={()=>navigation.navigate('NotificationPreferences')}><Ionicons name="options-outline" color="#ff6a1a" size={18}/><Text style={s.actionText}>Preferencias</Text></TouchableOpacity>{data.unread_count>0&&<TouchableOpacity style={s.action} onPress={readAll}><Ionicons name="checkmark-done-outline" color="#ff6a1a" size={18}/><Text style={s.actionText}>Leer todas</Text></TouchableOpacity>}</View>
    {!data.items.length?<View style={s.empty}><Ionicons name="notifications-off-outline" color="#4b4b52" size={42}/><Text style={s.emptyTitle}>Todo al día</Text><Text style={s.emptyBody}>Aquí aparecerán tus invitaciones, cambios de partido y avisos de EasyPass.</Text></View>:data.items.map(item=>{const[icon,color]=META[item.type]||['notifications-outline','#ff5a00'];return<TouchableOpacity key={item.id} activeOpacity={.8} style={[s.item,!item.read_at&&s.unread]} onPress={()=>openItem(item)}><View style={[s.icon,{backgroundColor:`${color}1c`}]}><Ionicons name={icon} color={color} size={21}/></View><View style={s.copy}><View style={s.titleRow}><Text style={s.itemTitle}>{item.title}</Text>{!item.read_at&&<View style={s.dot}/>}</View><Text style={s.body}>{item.body}</Text><Text style={s.date}>{dateLabel(item.created_at)}</Text></View></TouchableOpacity>;})}
  </ScrollView></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0b0b0d'},content:{padding:18,paddingBottom:110},back:{width:42,height:42,borderRadius:14,backgroundColor:'#202024',alignItems:'center',justifyContent:'center'},actions:{flexDirection:'row',gap:9,marginBottom:13},action:{flex:1,minHeight:43,borderRadius:13,borderWidth:1,borderColor:'#303035',backgroundColor:'#18181b',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},actionText:{color:'#ddd',fontSize:11,fontWeight:'900'},item:{flexDirection:'row',gap:12,backgroundColor:'#151517',borderWidth:1,borderColor:'#26262a',borderRadius:18,padding:14,marginBottom:9},unread:{backgroundColor:'#1b1715',borderColor:'#5e3018'},icon:{width:43,height:43,borderRadius:14,alignItems:'center',justifyContent:'center'},copy:{flex:1},titleRow:{flexDirection:'row',alignItems:'center',gap:8},itemTitle:{color:'#fff',fontSize:14,fontWeight:'900',flex:1},dot:{width:7,height:7,borderRadius:4,backgroundColor:'#ff5a00'},body:{color:'#929299',fontSize:12,lineHeight:17,marginTop:4},date:{color:'#5f5f66',fontSize:9,fontWeight:'800',marginTop:8,textTransform:'uppercase'},empty:{alignItems:'center',backgroundColor:'#151517',borderRadius:20,borderWidth:1,borderColor:'#252529',padding:32,marginTop:7},emptyTitle:{color:'#fff',fontSize:17,fontWeight:'900',marginTop:10},emptyBody:{color:'#77777e',fontSize:12,lineHeight:18,textAlign:'center',marginTop:6}});
