import React,{useCallback,useState}from'react';
import{ActivityIndicator,ScrollView,StyleSheet,Text,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{Ionicons}from'@expo/vector-icons';
import{api}from'../api/client';
import ScreenHeader from'../components/ScreenHeader';

export default function ReputationScreen({navigation}){
  const[data,setData]=useState(null),[error,setError]=useState('');
  const load=useCallback(()=>{setError('');api.get('/me/reputation').then(r=>setData(r.data.data)).catch(e=>setError(e.response?.data?.msg||'No se pudo cargar'));},[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  if(!data&&!error)return<View style={s.page}><ActivityIndicator color="#ff5a00" style={{marginTop:80}}/></View>;
  return<View style={s.page}><ScreenHeader title="Mi fiabilidad" onBack={()=>navigation.navigate('Profile')}/><ScrollView contentContainerStyle={s.content}>
    <View style={s.hero}><View style={s.ring}><Text style={s.rate}>{data?.attendance_rate||0}%</Text><Text style={s.rateLabel}>ASISTENCIA</Text></View><View style={{flex:1}}><Text style={s.heroEyebrow}>REPUTACIÓN POSITIVA</Text><Text style={s.heroTitle}>{reliabilityLabel(data)}</Text><Text style={s.heroText}>La fiabilidad reconoce la constancia. Tus incidencias concretas nunca se muestran públicamente.</Text></View></View>
    <View style={s.metrics}><Metric icon="checkmark-done" value={data?.completed_matches} label="Completados"/><Metric icon="time-outline" value={data?.early_cancellations} label="Avisadas a tiempo"/><Metric icon="calendar-outline" value={data?.attendance_opportunities} label="Convocatorias"/></View>
    <Text style={s.section}>DISTINTIVOS CONSEGUIDOS</Text>
    <View style={s.card}>{!data?.badges?.length?<View style={s.empty}><Ionicons name="ribbon-outline" color="#555" size={27}/><Text style={s.emptyText}>Completa partidos para conseguir tus primeros distintivos.</Text></View>:data.badges.map((badge,index)=><View key={badge.code} style={[s.badge,index>0&&s.divider]}><View style={s.badgeIcon}><Ionicons name={badge.icon} color="#ff6a1a" size={22}/></View><View style={{flex:1}}><Text style={s.badgeTitle}>{badge.label}</Text><Text style={s.badgeText}>{badge.description}</Text></View><Ionicons name="checkmark-circle" color="#4dbb78" size={21}/></View>)}</View>
    <Text style={s.section}>DETALLE PRIVADO</Text>
    <View style={s.privateCard}><PrivateRow label="Cancelaciones avisadas a tiempo" value={data?.early_cancellations}/><PrivateRow label="Cancelaciones tardías" value={data?.late_cancellations}/><PrivateRow label="Ausencias registradas" value={data?.no_shows}/><Text style={s.note}>Estos datos solo los ves tú y el equipo de EasyFutbol. Se utilizan para gestionar incidencias y mejorar la organización.</Text></View>
  </ScrollView></View>
}
const reliabilityLabel=(data)=>{if(!data?.attendance_opportunities)return'Empieza a construir tu historial';if(data.attendance_rate>=95)return'Fiabilidad excelente';if(data.attendance_rate>=85)return'Muy buen historial';if(data.attendance_rate>=70)return'Historial en progreso';return'Sigue sumando partidos';};
function Metric({icon,value,label}){return<View style={s.metric}><Ionicons name={icon} color="#ff6a1a" size={20}/><Text style={s.metricValue}>{Number(value||0)}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function PrivateRow({label,value}){return<View style={s.privateRow}><Text style={s.privateLabel}>{label}</Text><Text style={s.privateValue}>{Number(value||0)}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0b0b0d'},content:{padding:17,paddingBottom:110},hero:{backgroundColor:'#191817',borderRadius:24,borderWidth:1,borderColor:'#3a2d24',padding:19,flexDirection:'row',alignItems:'center',gap:17},ring:{width:92,height:92,borderRadius:46,borderWidth:7,borderColor:'#ff5a00',alignItems:'center',justifyContent:'center',backgroundColor:'#201a17'},rate:{color:'#fff',fontSize:23,fontWeight:'900'},rateLabel:{color:'#9b6a51',fontSize:7,fontWeight:'900',letterSpacing:.7},heroEyebrow:{color:'#ff6a1a',fontSize:9,fontWeight:'900',letterSpacing:1.2},heroTitle:{color:'#fff',fontSize:19,fontWeight:'900',marginTop:5},heroText:{color:'#85858b',fontSize:11,lineHeight:17,marginTop:5},metrics:{flexDirection:'row',gap:8,marginTop:11},metric:{flex:1,backgroundColor:'#171719',borderRadius:17,paddingVertical:14,alignItems:'center'},metricValue:{color:'#fff',fontSize:23,fontWeight:'900',marginTop:5},metricLabel:{color:'#76767d',fontSize:9,fontWeight:'800',marginTop:3,textAlign:'center'},section:{color:'#939399',fontSize:10,fontWeight:'900',letterSpacing:1.2,marginTop:26,marginBottom:10,marginLeft:2},card:{backgroundColor:'#171719',borderRadius:20,paddingHorizontal:16,borderWidth:1,borderColor:'#29292d'},badge:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:14},divider:{borderTopWidth:1,borderTopColor:'#29292d'},badgeIcon:{width:43,height:43,borderRadius:14,backgroundColor:'#2b211c',alignItems:'center',justifyContent:'center'},badgeTitle:{color:'#fff',fontWeight:'900'},badgeText:{color:'#77777d',fontSize:11,marginTop:4},empty:{alignItems:'center',padding:24,gap:9},emptyText:{color:'#777',fontSize:12,textAlign:'center'},privateCard:{backgroundColor:'#151517',borderRadius:20,padding:17},privateRow:{flexDirection:'row',justifyContent:'space-between',paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#262629'},privateLabel:{color:'#aaa',fontSize:12},privateValue:{color:'#fff',fontWeight:'900'},note:{color:'#66666d',fontSize:10,lineHeight:16,marginTop:14}});
