import React,{useCallback,useState}from'react';
import{ActivityIndicator,Alert,ScrollView,StyleSheet,Switch,Text,TouchableOpacity,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{Ionicons}from'@expo/vector-icons';
import{api}from'../api/client';
import ScreenHeader from'../components/ScreenHeader';
import{SocialAvatar}from'../components/social/SocialComponents';
export default function SocialPrivacyScreen({navigation}){const[data,setData]=useState(null),[saving,setSaving]=useState(false);const load=useCallback(()=>api.get('/social/privacy/me').then(r=>setData(r.data)).catch(()=>Alert.alert('Privacidad','No se pudo cargar')),[]);useFocusEffect(useCallback(()=>{load();},[load]));const setOption=async(key,value)=>{const privacy={...data.privacy,[key]:value};setData({...data,privacy});setSaving(true);try{await api.patch('/social/privacy/me',privacy);}catch(e){Alert.alert('Privacidad','No se pudo guardar');load();}finally{setSaving(false)}};const unblock=user=>Alert.alert('Desbloquear',`¿Permitir que ${user.name} vuelva a encontrarte?`,[{text:'Cancelar',style:'cancel'},{text:'Desbloquear',onPress:async()=>{try{await api.delete(`/social/blocks/${user.id}`);load();}catch(e){Alert.alert('Privacidad','No se pudo desbloquear');}}}]);if(!data)return<View style={s.page}><ActivityIndicator color="#ff5a00" style={{marginTop:80}}/></View>;return<View style={s.page}><ScrollView contentContainerStyle={s.content}><ScreenHeader eyebrow="CONTROL SOCIAL" title="Privacidad" description="Decide qué pueden ver tus amigos y gestiona los usuarios bloqueados." action={<TouchableOpacity style={s.back} onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" color="#fff" size={21}/></TouchableOpacity>}/><View style={s.card}><Option icon="calendar-outline" title="Próximos partidos" body="Permitir que tus amigos vean los partidos a los que estás apuntado." value={data.privacy.show_upcoming_to_friends} onChange={v=>setOption('show_upcoming_to_friends',v)}/><Option icon="stats-chart-outline" title="Estadísticas deportivas" body="Mostrar goles, asistencias y partidos ganados a tus amigos." value={data.privacy.show_stats_to_friends} onChange={v=>setOption('show_stats_to_friends',v)} divider/></View>{saving?<Text style={s.saving}>Guardando cambios…</Text>:<Text style={s.note}>Los cambios se aplican inmediatamente. Seguirás apareciendo en los partidos en los que participes.</Text>}<Text style={s.section}>USUARIOS BLOQUEADOS · {data.blocked.length}</Text><View style={s.card}>{!data.blocked.length?<View style={s.empty}><Ionicons name="shield-checkmark-outline" color="#555" size={28}/><Text style={s.emptyText}>No has bloqueado a nadie.</Text></View>:data.blocked.map((user,index)=><View key={user.id} style={[s.blocked,index>0&&s.divider]}><SocialAvatar uri={user.avatar_url} name={user.name} size={42}/><Text style={s.name}>{user.name}</Text><TouchableOpacity style={s.unblock} onPress={()=>unblock(user)}><Text style={s.unblockText}>Desbloquear</Text></TouchableOpacity></View>)}</View></ScrollView></View>}
function Option({icon,title,body,value,onChange,divider}){return<View style={[s.option,divider&&s.divider]}><View style={s.icon}><Ionicons name={icon} color="#ff6a1a" size={20}/></View><View style={{flex:1}}><Text style={s.title}>{title}</Text><Text style={s.body}>{body}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{false:'#33343a',true:'#9f410d'}} thumbColor={value?'#ff5a00':'#8a8b90'}/></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0b0b0d'},content:{padding:18,paddingBottom:110},back:{width:42,height:42,borderRadius:14,backgroundColor:'#202024',alignItems:'center',justifyContent:'center'},card:{backgroundColor:'#171719',borderRadius:21,borderWidth:1,borderColor:'#29292d',paddingHorizontal:16},option:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:17},divider:{borderTopWidth:1,borderTopColor:'#2a2a2e'},icon:{width:40,height:40,borderRadius:13,backgroundColor:'rgba(255,90,0,.11)',alignItems:'center',justifyContent:'center'},title:{color:'#fff',fontSize:14,fontWeight:'900'},body:{color:'#77777e',fontSize:11,lineHeight:16,marginTop:4},note:{color:'#68686e',fontSize:10,lineHeight:16,margin:12},saving:{color:'#ff6a1a',fontSize:10,fontWeight:'800',margin:12},section:{color:'#83838a',fontSize:10,fontWeight:'900',letterSpacing:1.1,marginTop:22,marginBottom:9},blocked:{flexDirection:'row',alignItems:'center',gap:11,paddingVertical:13},name:{color:'#fff',fontWeight:'800',flex:1},unblock:{borderWidth:1,borderColor:'#39393e',paddingHorizontal:10,paddingVertical:8,borderRadius:10},unblockText:{color:'#aaa',fontSize:10,fontWeight:'800'},empty:{alignItems:'center',paddingVertical:27,gap:8},emptyText:{color:'#777',fontSize:12}});
